AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template deploys the build process for the YoPass Back End.

Parameters:
  GitHubConnectionArn:
    Description: Can be found or created in CodePipeline console, settings, connections.
    Type: String
  EnvLabel:
    Description: Provide a unique label for your environment to identify resources.  You cannot use a name that is already in use.
    Type: String
  GitHubRepo:
    Type: String
    Description: GitHub repo name to build from
    Default: 'jhaals/yopass'
  GitHubBranch:
    Type: String
    Description: Name of the branch in the GitHub repo to build from.
    Default: 'master'
  GitHubTag:
    Type: String
    Description: Name of the Tag in the GitHub repo.
    Default: '11.5.0'  
  CreateS3Bucket:
    Type: String
    Description: Create the S3 bucket named 'codepipeline-artifact-store-{AWS::Region}-{AWS::AccountId}'?  Do not change this value if updating an existing stack.
    Default: 'Create the S3 Bucket'
    AllowedValues:
      - 'Create the S3 Bucket'
      - 'The S3 Bucket already exists'
  MasterStack:
    Description: Name of the master cloudformation stack
    Type: String


Conditions:
  DoCreateS3Bucket: !Equals [!Ref CreateS3Bucket, 'Create the S3 Bucket']

Resources: 
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Condition: DoCreateS3Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: EnvLabel
          Value: !Ref EnvLabel

  BuildDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'build-deployment-${AWS::AccountId}-${EnvLabel}'
      Tags:
        - Key: EnvLabel
          Value: !Ref EnvLabel

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AllowActions
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: 
                  - '*'
                Condition:
                  StringEqualsIfExists:
                    "iam:PassedToService":
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
              - Effect: Allow
                Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetRepository
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                  - codestar-connections:UseConnection
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                  - opsworks:CreateDeployment
                  - opsworks:DescribeApps
                  - opsworks:DescribeCommands
                  - opsworks:DescribeDeployments
                  - opsworks:DescribeInstances
                  - opsworks:DescribeStacks
                  - opsworks:UpdateApp
                  - opsworks:UpdateStack
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                  - devicefarm:ListProjects
                  - devicefarm:ListDevicePools
                  - devicefarm:GetRun
                  - devicefarm:GetUpload
                  - devicefarm:CreateUpload
                  - devicefarm:ScheduleRun
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                  - ecr:DescribeImages
                  - states:DescribeExecution
                  - states:DescribeStateMachine
                  - states:StartExecution
                  - appconfig:StartDeployment
                  - appconfig:StopDeployment
                  - appconfig:GetDeployment
                  - logs:CreateLogGroup
                  - logs:PutRetentionPolicy
                  - ssm:GetParameters
                Resource: '*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CodeBuildCloudFormation
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - logs:DescribeLogGroups
                  - iam:GetRole
                  - lambda:*
                  - apigateway:*
                  - s3:GetObject
                  - iam:PassRole
                Resource: '*'
        - PolicyName: CodeBuildCustomS3
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub 'arn:aws:s3:::build-deployment-${AWS::AccountId}-${EnvLabel}*'
        - PolicyName: CodeBuildBasePolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: !Sub 'arn:aws:s3:::codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}*'
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'


  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Location: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
        Type: S3
      Name: !Sub '${EnvLabel}-api-pipeline'
      RestartExecutionOnUpdate: True
      RoleArn: !GetAtt 'PipelineRole.Arn'
      Stages: 
        - Name: SourceStage
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              RunOrder: 1
              Configuration:
                BranchName: !Ref GitHubBranch
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'

        - Name: BuildStage
          Actions:
            - Name: Build
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration: 
                EnvironmentVariables: !Sub |
                  [
                      {
                          "name": "GITHUB_TAG",
                          "value": "${GitHubTag}",
                          "type": "PLAINTEXT"
                      }
                  ]
                ProjectName: !Ref CodeBuild
              OutputArtifacts: 
                - Name: BuildArtifact
              InputArtifacts: 
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: BuildVariables


  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${EnvLabel}-build'
      Description: !Sub 'Build project for ${EnvLabel}'
      Source: 
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
                GOOS: "linux"
          #       PUBLIC_URL: "http://eaedfi-yopass.s3-website.us-east-1.amazonaws.com"
          #       REACT_APP_BACKEND_URL: 'https://n8ue4uhn60.execute-api.us-east-1.amazonaws.com/test'
          phases:
            install:
              runtime-versions:
                golang: 1.18
                nodejs: 16
            
            build:
              commands:
                - git clone 'https://github.com/${GitHubRepo}.git' yopass
                - cd yopass
                - git checkout tags/${!GITHUB_TAG} 
                - cd deploy/aws-lambda 
                - ls -al              
                - go mod download github.com/gofrs/uuid
                - go get github.com/yopass/yopass-lambda
                - go build -o main
                - ls -al
                # Deploy to S3
                - zip -r main-${!CODEBUILD_BUILD_NUMBER}.zip main
                - aws s3 cp main-${!CODEBUILD_BUILD_NUMBER}.zip s3://build-deployment-${AWS::AccountId}-${EnvLabel}/
                - |-
                  aws cloudformation describe-stacks --stack-name ${MasterStack} | \
                  jq '.Stacks[0].Parameters' | \
                  jq --arg ver "${!CODEBUILD_BUILD_NUMBER}" '(.[] | select(.ParameterKey=="BuildNumber")).ParameterValue |= $ver' > params.json
                - cat params.json
                - aws cloudformation update-stack --stack-name ${MasterStack} --use-previous-template --parameters file://params.json

          artifacts:
            files:
              - yopass/deploy/aws-lambda/main
      Artifacts:
        Type: CODEPIPELINE
        Name: !Sub '${EnvLabel}-build'
      Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        ComputeType: BUILD_GENERAL1_MEDIUM
        PrivilegedMode: false
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: !GetAtt 'CodeBuildRole.Arn'
      TimeoutInMinutes: 15
      QueuedTimeoutInMinutes: 120
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub '/aws/codebuild/${EnvLabel}-build'
          Status: ENABLED
      Visibility: PRIVATE

